# -*- coding: utf-8 -*-
"""Dasboard Predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RzzDPWCqHuud0ETmpKnSftDCLtM87b0b
"""

import streamlit as st
import pandas as pd
from prophet import Prophet
import matplotlib.pyplot as plt

@st.chace_data
def load_data():
  df = pd.read_csv('df_clean_crypto.csv')
  df['ds'] = pd.to_datetime(df['ds'])
  return df

def train_prophet(df, selected_currency):
  open_col = f"{selected_currency}_USDT_1h_open"
  high_col = f"{selected_currency}_USDT_1h_high"
  low_col = f"{selected_currency}_USDT_1h_low"
  close_col = f"{selected_currency}_USDT_1h_close"

  df_model = df[['ds', open_col, high_col, low_col, close_col]].copy()
  df_model.rename(columns={close_col:'y'}, inplace=True)

  model = prophet(
      yearly_seasonality = True,
      weekly_seasonality = True,
      daily_seasonality = True,
      seasonality_mode = 'multiplicative'
      changepoint_prior_scale = 0.2,
      seasonality_prior_scale = 0.2,
      n_changepoints = 50
  )

  model.add_regressor(open_col)
  model.add_regressor(high_col)
  model.add_regressor(low_col)

  model.fit(df_model)
  return model, df_model, open_col, high_col, low_col

def predict_future(model, df_model, open_col, high_col, low_col, periods):
  future = model.make_future_dataframe(periods=periods, freq='D')

  last_open = df_model[open_col].iloc[-1]
  last_high = df_model[high_col].iloc[-1]
  last_low = df_model[low_col].iloc[-1]

  future[open_col] = last_open
  future[high_col] = last_high
  future[low_col] = last_low

  forecast = model.predict(future)
  return forecast

st.set_page_config(page_title="Crypto Currency Forecast", page_icon="📊", layout="wide")
st.title("📊 Crypto Forecast Dashboard")

st.warning("Forecast jangka panjang (>14 hari) dapat mengandung bias yang lebih besar. Gunakan dengan bijak.")

data = load_data()

st.sidebar.header("Pengaturan Forecast")
currencies = ['BTC', 'ETH', 'SOL', 'DOGE', 'BNB', 'XRP']
selected_currency = st.sidebar.selectbox("Pilih Currency", currencies)
periods = st.sidebar.selectbox("Periode Forecast (Hari)", [7, 14, 30])

model, df_model, open_col, high_col, low_col = train_prophet(data, selected_currency)
forecast = predict_future(model, df_model, open_col, high_col, low_col, periods)

st.subheader(f"Forecast {selected_currency} untuk {periods} Hari ke Depan")
fig1 = model.plot(forecast)
st.pyplot(fig1)

st.subheader("Tabel Hasil Forecast")
st.dataframe(forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(periods))

st.subheader("Ringkasan Prediksi")
col1, col2, col3 = st.columns(3)
col1.metric("Prediksi Harga Akhir", f"{forecast['yhat'].iloc[-1]:.2f}")
col2.metric("Batas Atas", f"{forecast['yhat_upper'].iloc[-1]:.2f}")
col3.metric("Batas Bawah", f"{forecast['yhat_lower'].iloc[-1]:.2f}")

st.caption("Dibuat dengan ❤️ menggunakan Prophet dan Streamlit.")
